name: E2E Tests

on:
  workflow_dispatch:

jobs:
  test-e2e-golang:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        go-version: [ '1.22.x' ]

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install Dependencies
        run: | 
          cd ./test/e2e/golang
          go mod download

      - name: Run E2E Golang Tests
        env:
          XMR_SPEND_WALLET_PASSWORD: ${{ secrets.XMR_SPEND_WALLET_PASSWORD }}
          XMR_WALLET_RPC_ADDRESS: ${{ secrets.XMR_WALLET_RPC_ADDRESS }}
          XMR_WALLET_RPC_USER: ${{ secrets.XMR_WALLET_RPC_USER }}
          XMR_WALLET_RPC_PASS: ${{ secrets.XMR_WALLET_RPC_PASS }}
        run: | 
          cd ./test/e2e/golang
          go test ./test